static char const * const format_string_jugador =
"["
"{"
"    \"_id\": %d,\r\n"
"    \"nombre\": \"%s\",\r\n"
"    \"foto\": \"./imagenes/perfil/%s.png\",\r\n"
"    \"dinero\": %f,\r\n"
"    \"trayectoria\": {\r\n"
"        \"victorias\": %d,\r\n"
"        \"derrotas\": %d,\r\n"
"        \"empates\": %d\r\n"
"    },\r\n"
"    \"equipo\": {\r\n"
"        \"nombre\": \"%s FC\",\r\n"
"        \"escudo\": \"./imagenes/escudos/player/%s.png\",\r\n"
"        \"miembros\": {\r\n"
"            \"entrenador\": {%s},\r\n"
"            \"futbolista\": [\r\n"
"                {%s},\r\n"
"                {%s},\r\n"
"                {%s},\r\n"
"                {%s},\r\n"
"                {%s},\r\n"
"                {%s},\r\n"
"                {%s},\r\n"
"                {%s},\r\n"
"                {%s},\r\n"
"                {%s},\r\n"
"                {%s}\r\n"
"            ]\r\n"
"    }\r\n"
"}\r\n"
"]\r\n"
"\r\n"
;
